// Original launch plan, used only to seed the database.
export const SEED_POSTS = [
{id:"p01",n:1,t:"Pull Up a Seat",p:"seat",s:"",pl:"LinkedIn + Instagram",f:"Short animation · 8s loop",sz:["1080×1350 feed","1080×1920 Stories"],d:"2026-10-06",
obj:"Introduce Creative Seat and plant the chair as the brand’s signature device.",
idea:"A top-down view of a long meeting table surrounded by mismatched chairs, each tagged with a marketing role. One gap sits conspicuously empty. A new chair rolls in from off-frame, spins once and clicks into place. The team is complete.",
ad:[["Composition","Strict bird’s-eye view. The table runs diagonally top-left to bottom-right on a paper ground. Eight chairs around it, each a different design (mesh task chair, bentwood, beanbag) to suggest a real, human team."],
["Labels","Small pill tags on each chair: CONTENT, SOCIAL, BRAND, PERFORMANCE, CRM, EVENTS, PR. The gap has no tag, just a faint dotted outline where a chair should be."],
["Hero chair","Volt green, softly rendered in clay-like 3D, tagged “DESIGN · ILLUSTRATION · ANIMATION”."],
["Movement","0–2s static; the eye finds the gap. 2–4s the volt chair glides in with slight overshoot and one 360° spin. 5s it settles and the cups and laptops give a tiny synchronised bounce. 6–8s the headline fades up beneath."]],
eye:"The dotted gap, then the volt chair.",hold:"No people, no logos on the table, no confetti. The only saturated colour in frame is the volt chair.",
copy:[["Headline","Marketing team: complete."],["Sub-line","Creative Seat — design, illustration and animation, on demand."]],
li:"Most marketing teams we speak to have a gap at the table.\n\nNot a gap in ideas. A gap in people who can make them: the designer who isn’t overloaded, the illustrator you don’t have, the animator you’ve never been able to justify.\n\nCreative Seat fills that seat. One ongoing creative team for design, illustration and animation, working as part of yours. No hiring round. No freelancer roulette.\n\nWe’re new here. Pull up a chair.",
ig:"Every team has a gap at the table. We’re the chair that fits it.\n\nDesign. Illustration. Animation. On demand."},

{id:"p02",n:2,t:"Now Serving 04",p:"backlog",s:"",pl:"LinkedIn lead, Instagram",f:"Conceptual static",sz:["1080×1350"],d:"2026-10-08",
obj:"Make marketing teams instantly recognise the creative queue they’re stuck in.",
idea:"A red deli-counter ticket dispenser. The display reads “NOW SERVING 04”. The ticket being pulled reads “47”, labelled “Your design request”. Anyone who’s waited on a design team gets it in half a second.",
ad:[["Composition","The dispenser, photographed or photo-real, dead centre at eye level, filling the upper 60% of frame. One paper ticket curls toward the viewer in sharp focus."],
["Ground","Flat forest green. One overhead spotlight gives it gallery gravity."],
["Display","Glowing volt LED digits for “04”. The only bright colour besides the ticket."],
["Type","Headline set small in the bottom quarter, so the tiny line against the big object creates the joke. The ticket’s “47” in a chunky condensed numeral with slight print misregistration."]],
eye:"The “47” on the ticket, then up to “04”.",hold:"No hands, no queue of people, no clock. The numbers do the work.",
copy:[["Ticket","YOUR DESIGN REQUEST — No. 47"],["Display","NOW SERVING 04"],["Headline","Your brief is in the queue. Somewhere."]],
li:"There’s usually nothing wrong with the design team. There’s just one of them, and forty-six requests ahead of yours.\n\nThe queue is invisible until you add it up: the event banner, the sales one-pager, the three social variants, the “small” website update. Each one is quick. Together they’re a backlog.\n\nWe built Creative Seat so the queue moves. Extra design, illustration and animation capacity that plugs into your team and works through the list.\n\nWhat number is your brief?",
ig:"Now serving: someone else’s brief.\n\nMore capacity, shorter queue. That’s the whole idea."},

{id:"p03",n:3,t:"One Seat. Three Disciplines.",p:"service",s:"",pl:"LinkedIn + Instagram",f:"Carousel · 6 slides",sz:["1080×1350 × 6"],d:"2026-10-13",
obj:"Explain what Creative Seat is and how it works in under 30 seconds of swiping.",
idea:"One volt chair on slide 1 splits into three chairs across the middle slides, one per discipline, then reassembles as a single seat at the client’s table. The carousel’s structure mirrors the product: one seat, three skills.",
ad:[["System","Every slide: paper ground, small page counter top-right (“01/06”), the volt chair in the same clay 3D style as Post 1."],
["Slide 1","One chair centred, headline above in large sans with the second line in Instrument Serif italic."],
["Slides 2–4","The chair restyled per discipline: crisp vector (design), hand-drawn ink (illustration), motion-blurred mid-spin (animation). Each has a pill tag, one short line and three example deliverables."],
["Slide 5","A simple horizontal flow drawn with volt lines: Brief → Seat → Work → Next brief."],
["Slide 6","Forest ground, the chair back at the meeting table from Post 1, CTA in paper."]],
eye:"The headline on each slide, then the chair. Under 20 words of supporting copy per slide.",hold:"No pricing tables, no icon grids, no feature bullets. One idea per slide.",
copy:[["Slide 1","One seat. Three disciplines."],["Slide 2","DESIGN — Campaigns, social, decks, digital. The everyday work that keeps marketing moving."],["Slide 3","ILLUSTRATION — Custom visuals that make your brand look like no one else’s."],["Slide 4","ANIMATION — Motion for social, product, explainers and ads. Without hiring an animator."],["Slide 5","Send the brief. We make it. You approve it. Repeat."],["Slide 6","Your team, plus one. Take a seat → [website URL]"]],
li:"The short version of what we do.\n\nCreative Seat gives your marketing team ongoing access to designers, illustrators and animators. You brief us the way you’d brief a colleague, we make the work, and you keep moving.\n\nNo recruitment. No managing five freelancers across five time zones. One seat that covers three disciplines.\n\nIf your team has more ideas than hands, swipe through and then let’s talk.",
ig:"Design. Illustration. Animation. One seat at your table.\n\nSwipe for how it works."},

{id:"p04",n:4,t:"Seat No. 01 — The Illustrator’s Chair",p:"seat",s:"Seat No.",pl:"Instagram lead, LinkedIn",f:"Illustration static",sz:["1080×1350","Optional 4s Story: the line draws itself"],d:"2026-10-20",
obj:"Open the Seat No. series and prove illustration craft with a piece people want to save.",
idea:"A chair that’s still being drawn. Front legs and seat fully rendered in rich, textured colour; toward the back the drawing dissolves into loose pencil construction lines and finally a single line trailing off the frame.",
ad:[["Composition","Chair dead centre at three-quarter view on a flat soft-lime field, about 45% of frame. Generous space so it feels like a print."],
["Style","Gouache-like texture, visible brush grain, warm shadows. Rendering fades left to right: full colour → graphite sketch → one continuous line."],
["Series frame","Top-left label “SEAT No. 01 — ILLUSTRATION”. Bottom-centre caption in Instrument Serif italic. Keep this camera angle and scale for every Seat No. post."]],
eye:"The seam where colour turns to pencil. That seam is the idea.",hold:"No props, no logo inside the artwork, no drop shadows. It should read as a limited-edition print.",
copy:[["Label","SEAT No. 01 — ILLUSTRATION"],["Line","Drawn to order."]],
li:"Stock imagery makes brands look like each other. Illustration makes them look like themselves.\n\nThis is Seat No. 01, the first in a series of chairs we’re making to show each of our disciplines. It’s also a small reminder that custom illustration doesn’t need an in-house illustrator. It needs a seat.",
ig:"Seat No. 01: The Illustrator’s Chair.\n\nFirst in a series of chairs, each made in the language of a discipline. This one’s still being drawn, which is roughly how every illustration brief feels at 60%.\n\nCustom illustration for campaigns, brands and content. Seat No. 02 lands soon."},

{id:"p05",n:5,t:"Where Good Ideas Go to Wait",p:"backlog",s:"",pl:"LinkedIn lead, Instagram",f:"Typographic static · UI parody",sz:["1080×1350"],d:"2026-10-22",
obj:"Make marketing leaders feel the cost of ideas that never got made.",
idea:"A desktop file window showing a folder called “Campaign ideas”. Inside: a row of campaign folders, each marked “(never made)”. It’s funny because everyone has this folder.",
ad:[["Composition","One oversized file-explorer window floating centre on a forest field, corners slightly rounded. Chrome faithful but simplified, no OS branding."],
["Hierarchy","Folder names at a generous size. “(never made)” set in volt so the pattern jumps down the list. The last line’s “(let’s see)” in Instrument Serif italic."],
["Detail","Date-modified column stretches back 18 months. A tiny chair icon replaces the folder icon on the last row only, a quiet hint."],
["Headline","Above the window in paper-coloured sans."]],
eye:"The column of volt “(never made)” tags.",hold:"No cursor, no hand, no mock notifications. It should read like a screenshot someone’s embarrassed to share.",
copy:[["Headline","Where good ideas go to wait."],["Folder","Campaign ideas"],["Rows","Q1_brand_film (never made) · Q2_illustrated_series (never made) · Q3_launch_animation (never made) · Q4_ideas_v2_FINAL (let’s see)"]],
li:"Every marketing team has this folder.\n\nThe ideas were good. They got sign-off. Then they met the production calendar, and the calendar was already full of banners.\n\nThe cost of limited creative capacity isn’t only slow delivery. It’s the campaigns that never exist: the animation nobody could make, the illustrated series that stayed a moodboard.\n\nWhat’s in your folder? We’d like to make it.",
ig:"We all have this folder.\n\nLet’s empty it."},

{id:"p06",n:6,t:"Brief → Built #1: The Webinar",p:"work",s:"Brief → Built",pl:"LinkedIn + Instagram",f:"Carousel · 7 slides",sz:["1080×1350 × 7","Slide 5 may carry a short video"],d:"2026-10-27",
obj:"Prove that a vague, real-world brief comes back as a complete, polished kit.",
idea:"Slide 1 is the brief exactly as it arrived, one Slack message: “can we make the webinar look less boring? it’s on the 14th 😬”. The following slides unpack what came back. One sentence in, a whole campaign out.",
ad:[["Slide 1","The Slack-style message at large scale on paper, lightly anonymised (initials only). Nothing else. Let the emoji land."],
["Transition","A volt arrow sweeps across the slide edge into slide 2. This wipe is the series signature."],
["Slides 2–6","One deliverable per slide, gallery-style on forest with 120px margins, caption strip below: “KEY VISUAL · DESIGN”, “SPEAKER CARDS · DESIGN + ILLUSTRATION”, “COUNTDOWN · ANIMATION”."],
["Slide 7","Spec strip: “1 BRIEF → 14 ASSETS · 3 DISCIPLINES · 5 WORKING DAYS” (use the job’s real numbers)."],
["Source","A real job with client permission, or a self-initiated brief clearly labelled as a concept."]],
eye:"The contrast between the one-line brief and the richness of slide 2.",hold:"No process diagrams or moodboards here. Brief and result, nothing in between.",
copy:[["Slide 1","[the Slack message] — BRIEF → BUILT #1"],["Slide 2","The key visual."],["Slide 3","Speaker cards."],["Slide 4","Social cutdowns, every format."],["Slide 5","A 6-second countdown."],["Slide 6","Email header and landing banner."],["Slide 7","1 brief. 14 assets. 5 days. Less boring."]],
li:"The best briefs are sometimes one line long.\n\nThis one came in on Slack with an emoji and a deadline. Here’s what came back: key visual, speaker cards, social in every format, an animated countdown and email assets. Design, illustration and animation from one seat.\n\nYou don’t need a perfect brief to work with us. You need to tell us what “less boring” means to you, and we’ll take it from there.",
ig:"Brief → Built #1.\n\nOne Slack message. Fourteen assets. Swipe for the full kit."},

{id:"p07",n:7,t:"The Freelancer Merry-Go-Round",p:"backlog",s:"",pl:"LinkedIn + Instagram",f:"Motion loop · 6s seamless",sz:["1080×1350","1080×1920"],d:"2026-11-03",
obj:"Name the hidden admin cost of finding and managing freelancers, with humour instead of complaint.",
idea:"A fairground carousel carrying office chairs instead of horses. Each chair has a swing tag: “Booked till March”, “Ghosted”, “Great, but £££”, “On sabbatical”, “Only does logos”. It spins forever and none of the chairs is available.",
ad:[["Composition","Three-quarter view of a small, toy-like carousel dead centre on a soft-lime ground. Striped canopy in forest and paper. Five chairs on poles rising and falling out of phase."],
["Style","Soft matte clay 3D with slightly exaggerated proportions, like a desk toy."],
["Movement","Constant gentle rotation, each chair bobbing on its pole. Tags flutter with a slight lag. Invisible loop point. Each tag legible for at least 1.2s as it passes the front."],
["Type","Headline top-left in forest sans, two lines, second line in Instrument Serif italic. Small caps text on the tags."]],
eye:"Whichever tag is passing the front. The rotation is the reading order.",hold:"No fairground lights, no sparkle, no faces. Three colours plus the tags’ paper.",
copy:[["Headline","Finding a freelancer? Round and round we go."],["Tags","BOOKED TILL MARCH · GHOSTED · GREAT, BUT £££ · ON SABBATICAL · ONLY DOES LOGOS"]],
li:"Freelancers are brilliant. Finding, briefing, chasing and replacing them every few months is a part-time job nobody applied for.\n\nThe illustrator’s fully booked. The animator went quiet. The designer is great but only has Tuesdays.\n\nCreative Seat is one team that stays: the same people learning your brand, with design, illustration and animation under one roof. You brief once, not five times.\n\nStep off the ride whenever you like.",
ig:"The freelancer merry-go-round. Fun for about one lap.\n\nOne team. All three disciplines. Same seat every time."},

{id:"p08",n:8,t:"Seat No. 02 — The Animator’s Chair",p:"work",s:"Seat No.",pl:"Instagram lead, LinkedIn",f:"Frame-by-frame animation · 5s loop",sz:["1080×1350","1080×1920"],d:"2026-11-05",
obj:"Prove animation craft with a character performance that makes people watch twice.",
idea:"A chair with personality. It squashes as if landing from a jump, stretches, anticipates, bounces and settles, performing the classic principles of animation. Giving life to things is exactly what an animator does.",
ad:[["Series frame","Same framing as Seat No. 01: centred, three-quarter view, same scale and camera height. Flat volt field so the set reads as a collection."],
["Style","Hand-drawn 2D at 12fps on twos, visible line boil. Paper fill, forest line."],
["Movement","0–1s drops in and squashes on impact. 1–2s stretches up, anticipates. 2–3.5s big bounce with a mid-air half-turn. 3.5–5s lands, wobbles, settles to a hold matching frame 1."],
["Detail","Label top-left “SEAT No. 02 — ANIMATION”. Faint onion-skin ghost frames trail the chair during the jump."]],
eye:"The squash on landing. It’s the moment people replay.",hold:"No face on the chair, no background, nothing that needs sound. Character comes from motion alone.",
copy:[["Label","SEAT No. 02 — ANIMATION"],["Line","Everything moves better with an animator."]],
li:"Most marketing teams don’t have an animator, so motion is usually the first thing cut from the plan.\n\nThat’s a shame, because motion is what stops a thumb. This is Seat No. 02, a chair doing what our animators do every day: bringing still things to life.\n\nIf motion keeps falling off your plan, it doesn’t have to.",
ig:"Seat No. 02: The Animator’s Chair.\n\nSquash, stretch, anticipation, a little too much bounce. Twelve frames a second, drawn by hand.\n\nSocial motion, product animation, explainers and ads. Without hiring an animator."},

{id:"p09",n:9,t:"PSA No. 01: One Campaign. Forty-Three Sizes.",p:"backlog",s:"Marketing PSA",pl:"LinkedIn lead, Instagram",f:"PSA poster static",sz:["1080×1350"],d:"2026-11-10",
obj:"Make the invisible workload of format adaptation visible in one glance.",
idea:"One campaign key visual repeated 43 times in a tight grid, each at a different real-world ratio: 1:1, 4:5, 9:16, 16:9, leaderboard, skyscraper, email header, six-sheet. They shrink down the grid until the last is a speck.",
ad:[["Grid","Top 80% of the poster, packed like a contact sheet on paper with 4px gutters. Inside each tile, one bold invented campaign visual so repetition reads as pattern."],
["Scale","Tiles start large top-left and shrink toward bottom-right. The final tile is 6px wide with a tiny annotation: “43. favicon?”"],
["Texture","Light halftone and paper grain over the whole poster for a vintage public-information feel."],
["PSA footer","Solid band, 20% height. “Creative Seat” left, “Public Service Announcement No. 01” centre, “For Marketing Teams” right. Keep this layout for every PSA."],
["Headline","Large sans across the upper grid, ink on a paper knock-out bar."]],
eye:"The headline, then down the shrinking diagonal to the speck.",hold:"No real brand logos in tiles, no numbers on every tile (only the last), no device mockups.",
copy:[["Headline","One campaign. Forty-three sizes."],["Footer","Creative Seat · Public Service Announcement No. 01 · For Marketing Teams"],["Annotation","43. favicon?"]],
li:"Public Service Announcement No. 01.\n\nThe campaign was signed off in one meeting. Then came the 1:1, the 4:5, the 9:16, the LinkedIn banner, the email header, the display set, the event screen and the “can we also get a portrait one?”\n\nAdaptation is where creative capacity quietly disappears. It isn’t the big idea that clogs the team, it’s the forty-two versions of it.\n\nWe do the big idea and all forty-three sizes. Your designer can go back to the interesting work.",
ig:"PSA No. 01: the campaign is never one campaign.\n\nWe’ll do the resizes. All of them."},

{id:"p10",n:10,t:"The Seating Plan",p:"seat",s:"",pl:"LinkedIn + Instagram",f:"Typographic parody static",sz:["1080×1350"],d:"2026-11-17",
obj:"Build wit and memorability with a parody people will share for the joke alone.",
idea:"A formal wedding seating plan on an easel, but for a marketing department. Tables are Leadership, Brand, Performance, Content, Events. Table 6, “Creative”, lists one overworked guest and a lot of empty lines.",
ad:[["Composition","A real seating-plan board on a gilt easel, shot straight-on, 80% of frame, against a soft-focus forest backdrop with warm reception lighting."],
["Type","Instrument Serif italic for table names, a delicate sans for guest lists, mimicking wedding stationery."],
["Detail","Tables 1–5 full with 6–8 guests each. Table 6 has one guest and five blank lines. In the margin, pencilled in Caveat hand-lettering: “reserved for Creative Seat?”"],
["Accent","A single volt ribbon tied to the easel is the only brand colour."]],
eye:"Table 6’s blank lines, then the pencilled note.",hold:"No flowers, no confetti, no champagne. Keep the stationery perfectly straight-faced.",
copy:[["Board title","The Marketing Department — Seating Plan"],["Tables 1–5","Leadership · Brand · Performance · Content · Events"],["Table 6","Creative: Sam — Designer (also illustrator, also animator, also resizes). [five blank lines]"],["Pencil note","reserved for Creative Seat?"]],
li:"We found the seating plan for most marketing departments.\n\nFive tables of strategists, planners and channel owners, all generating briefs. One table for the people who make them, with one guest.\n\nIt’s not that teams don’t value creative. It’s that creative headcount rarely grows at the same pace as everything else.\n\nTable 6 has space. We’d love an invite.",
ig:"Table 6 is looking a bit empty.\n\nRSVP: Creative Seat."},

{id:"p11",n:11,t:"Friday, 16:52",p:"backlog",s:"",pl:"LinkedIn lead",f:"UI motion · 10s",sz:["1080×1350 native video","1080×1920"],d:"2026-11-19",
obj:"Hit a universally recognised moment of pain with humour that makes people tag a colleague.",
idea:"A clock ticks toward 17:00 on a Friday. At 16:52 a chat notification slides in: “Quick one — could we get this animated for Monday? 🙏”. The minute hand freezes and the notification multiplies into a stack of quick ones. A chair turns to face the screen.",
ad:[["Composition","A large minimal wall clock centred on paper, 50% of frame. Notification cards slide in top-right as a clean, generic chat UI with no real app branding."],
["Movement","0–3s second hand sweeps, small label “FRI 16:52”. 3–4s notification arrives with a soft bounce. 4–7s minute hand stops dead, five more quick ones stack in rhythm. 7–10s the stack clears and a volt chair swivels in bottom-right as the end line appears."],
["Pacing","Hold the frozen clock a full second before the stack. The pause is the joke."],
["Type","Notification text at UI scale in sans. End line large in Instrument Serif italic."]],
eye:"The first notification.",hold:"Must work with sound off. No sad-face emoji beyond the one in the message.",
copy:[["Time label","FRI 16:52"],["Notification 1","Quick one — could we get this animated for Monday? 🙏"],["Stack","Quick one — new sizes? · Quick one — can the logo be bigger? · Quick one — deck by 9am? · Quick one — one more version?"],["End line","We’ll take the quick ones."]],
li:"There’s no such thing as a quick one at 16:52 on a Friday.\n\nMost creative overload doesn’t come from big campaigns. It comes from a steady drip of small, reasonable requests, each landing on the same one or two people.\n\nThat’s the work Creative Seat is built for: the steady flow, not just the big moments. Send it over. Have your weekend.",
ig:"Friday, 16:52. You know the message."},

{id:"p12",n:12,t:"Brief → Built #2: The Launch",p:"work",s:"Brief → Built",pl:"Instagram lead (Reel), LinkedIn",f:"Reel · ~20s",sz:["1080×1920","1080×1350 crop for LinkedIn"],d:"2026-11-24",
obj:"Show motion and campaign thinking together by turning a short launch brief into a finished animation.",
idea:"Opens on a three-line email brief: a product launch, 15 seconds for social, a brand that’s “quite serious, but we want it to feel exciting”. It snaps through storyboard, styleframes and animatic, then plays the finished 15-second animation in full.",
ad:[["0–3s","The email on paper, readable, with three phrases highlighted in volt as they’re read: “15 seconds”, “quite serious”, “feel exciting”. That’s the creative tension."],
["3–5s","Volt arrow wipe, then rapid-fire thumbnails: storyboard, two styleframes, grey animatic, about 0.5s each with labels."],
["5–20s","The finished 15-second product animation, full-bleed and uninterrupted."],
["End card","Spec strip: “1 BRIEF → 15s ANIMATION · 4 CUTDOWNS · [X] DAYS”."],
["Source","A real job with permission, or a self-initiated concept clearly labelled."]],
eye:"The three highlighted phrases. They set up the payoff.",hold:"No voiceover about process, no talking heads. The work carries it.",
copy:[["Opening","BRIEF → BUILT #2"],["Brief","[the email, as written]"],["Process labels","STORYBOARD · STYLEFRAME · ANIMATIC"],["End card","Serious brand. Exciting launch. 1 brief → 15s animation · 4 cutdowns · [X] days"]],
li:"A three-line brief, and the most interesting tension in it was right there: a serious brand that wanted a launch to feel exciting.\n\nThat’s what good animation solves. It can add energy without losing credibility, and explain a product faster than a paragraph can.\n\nFrom email to finished animation and four cutdowns, all from one seat.",
ig:"Brief → Built #2.\n\n“Quite serious, but exciting” is our favourite kind of brief. Here’s what 15 seconds of that looks like."},

{id:"p13",n:13,t:"The Chair Test",p:"work",s:"",pl:"Instagram lead, LinkedIn",f:"Carousel · 10 slides",sz:["1080×1350 × 10"],d:"2026-12-01",
obj:"Show stylistic range, so no brand thinks “they don’t do our kind of look”.",
idea:"One ordinary chair, drawn nine completely different ways. Same subject, nine visual languages. The audience swipes, picks a favourite, and pictures their own brand in one of them.",
ad:[["Slide 1","A 3×3 grid of all nine chairs as small tiles on paper, even 24px gutters, like a specimen sheet. Headline above."],
["Slides 2–10","One style per slide, full frame, on the ground that suits it. Label bottom-left: “STYLE 03 / 09 — PAPER COLLAGE”."],
["The nine","Risograph (two-colour, misregistered) · Soft clay 3D · Single continuous line · Paper collage · Pixel art 32×32 · Loose watercolour · Crisp isometric vector · Linocut · A chair built from letterforms."],
["Consistency","Same chair model, angle and scale in every style, so style is the only variable."]],
eye:"The grid’s variety, then the clay 3D tile, coloured volt so it pops.",hold:"Don’t imitate any named artist’s signature style. These are techniques, not tributes.",
copy:[["Slide 1","One chair. Nine ways to draw it."],["Slides 2–9","STYLE 01 / 09 — RISOGRAPH … through STYLE 08 / 09 — LINOCUT"],["Slide 10","STYLE 09 / 09 — TYPOGRAPHIC. Which one’s your brand?"]],
li:"One question we hear a lot: “But can you do our style?”\n\nSo we drew one chair nine different ways. Same subject, nine completely different brand feelings.\n\nA good creative team doesn’t have a house style it imposes on you. It has range, and the judgement to know which style fits your brand, audience and channel.\n\nWhich number would your brand be?",
ig:"The Chair Test. Same chair, nine styles.\n\nRiso, clay, line, collage, pixel, watercolour, isometric, linocut and type. Which one would you pick? Tell us a number."},

{id:"p14",n:14,t:"The Headcount Maths",p:"service",s:"",pl:"LinkedIn lead",f:"Typographic static",sz:["1080×1350"],d:"2026-12-03",
obj:"Position Creative Seat clearly against the alternative of hiring three specialists.",
idea:"A simple equation set like a school maths problem. Three chair icons (designer, illustrator, animator) add up to a crowded list of hiring overheads. Below it, one volt chair equals “1 seat”.",
ad:[["Composition","Two stacked equations on paper, separated by “or” in Instrument Serif italic. Top equation in ink; bottom in volt with an ink outline."],
["Type","Large sans numerals and operators at the same weight as the chair icons, so icons and type read as one line."],
["Density","The top equation’s list is long and slightly crowded. The bottom has deliberate white space around it. The contrast in density is the argument."]],
eye:"The single volt chair.",hold:"No salary figures or pricing claims unless you have real numbers to cite.",
copy:[["Top","[designer] + [illustrator] + [animator] = 3 job specs · 3 hiring rounds · 3 salaries · 3 laptops · 3 onboardings"],["Middle","or"],["Bottom","[volt chair] = 1 seat."],["Footer","Design. Illustration. Animation. Creative Seat."]],
li:"The headcount maths most Heads of Marketing run in their heads.\n\nYou need design, illustration and animation, but not always all three at full-time capacity. Hiring three specialists is expensive and slow. Hiring one generalist means two disciplines get stretched.\n\nCreative Seat is the third option: ongoing access to all three disciplines, flexing to what your plan needs each month.\n\nIf you’re doing this maths right now, let’s talk it through.",
ig:"Three hires, or one seat.\n\nWe know which maths we prefer."},

{id:"p15",n:15,t:"Seat No. 03 — The Designer’s Chair",p:"seat",s:"Seat No.",pl:"LinkedIn + Instagram",f:"Static + 4s subtle motion",sz:["1080×1350","Motion version 1080×1350"],d:"2026-12-08",
obj:"Complete the core Seat No. trio and prove design craft through precision and system thinking.",
idea:"A chair built out of design itself: layout grids, guides, bezier handles, anchor points and a baseline grid, shown as if selected in a design tool mid-construction.",
ad:[["Series frame","Same framing and scale as Seats 01 and 02, on a paper field (so the three read soft lime, volt, paper)."],
["Style","Crisp vector. A clean forest path with visible anchor points and bezier handles highlighted in volt, as though selected."],
["Detail","A faint 12-column grid behind the chair at 5% opacity. Measurement annotations (“48”, “96”, “8pt”) sit on the guides."],
["Motion version","Guides slide in and snap with a tiny overshoot, one handle adjusts the backrest curve, the grid fades in last."]],
eye:"The volt selection handles.",hold:"No tool UI chrome (toolbars, panels). Just the object and its construction.",
copy:[["Label","SEAT No. 03 — DESIGN"],["Line","Every pixel on purpose."]],
li:"Seat No. 03: The Designer’s Chair.\n\nGood design is mostly invisible structure: grids, spacing, hierarchy and a lot of small decisions nobody notices when they’re right.\n\nThat’s the everyday work that keeps marketing running. Campaigns, social, decks, digital, all built on a system that holds together across every format.\n\nThat completes the core set: drawn, animated, designed. One seat covers all three.",
ig:"Seat No. 03: The Designer’s Chair.\n\nGrids, guides and a few hundred decisions you’ll never notice. That’s the point."},

{id:"p16",n:16,t:"PSA No. 02: The Empty Chair",p:"backlog",s:"Marketing PSA",pl:"LinkedIn lead, Instagram",f:"PSA poster static",sz:["1080×1350"],d:"2026-12-15",
obj:"Connect the missing creative resource to the ideas that die in planning meetings.",
idea:"A meeting room just after planning. A whiteboard crammed with brilliant ideas. Chairs pushed back. One chair was never used, and a yellow sticky note on it reads “who’s making this?”.",
ad:[["Composition","Slightly elevated wide-angle view. Whiteboard fills the back wall, table runs toward camera. The unused chair in the foreground bottom-right, sharpest in focus."],
["Image treatment","Vintage colour photo feel: warm faded greens, film grain, slight halftone, like a 1970s public-information leaflet. Staged photo or painterly render, but it must feel analogue."],
["PSA footer","Same layout as PSA No. 01, in a different band colour."],
["Headline","Large paper-coloured sans, top-left, over the image."]],
eye:"The sticky note on the empty chair.",hold:"No people in the room. The absence is the point.",
copy:[["Headline","Every planning meeting has one empty chair."],["Sticky note","who’s making this?"],["Footer","Creative Seat · Public Service Announcement No. 02 · For Marketing Teams"]],
li:"Public Service Announcement No. 02.\n\nThe planning session goes brilliantly. The whiteboard is full. Then someone asks the question that quietly edits the plan down: “who’s actually going to make this?”\n\nThe ideas that survive are usually the ones that fit current capacity, not necessarily the best ones.\n\nWe’d like to be the answer to that question. Next planning session, save us a seat.",
ig:"PSA No. 02: the best idea in the room needs someone to make it."},

{id:"p17",n:17,t:"One Seat. Every Shape.",p:"seat",s:"Seat No.",pl:"Instagram lead (Reel), LinkedIn",f:"Morph animation · 12s loop",sz:["1080×1920","1080×1350 crop"],d:"2026-12-17",
obj:"Unify the Seat No. series into one brand moment that shows all three disciplines are one service.",
idea:"A continuous morph loop. The drawn chair becomes the bouncing animated chair, which snaps into the precise vector chair, which dissolves back into pencil lines. The ground shifts soft lime → volt → paper with each change.",
ad:[["Composition","Locked-off camera, chair dead centre, identical scale to the series, so the morph reads as transformation, not a cut."],
["Movement","Each discipline holds 3s; each transition takes 1s. Pencil lines thicken into cartoon outlines and the chair hops; mid-hop it freezes into vector and guides snap round it; anchor points soften into graphite; loop."],
["Type","The top-left label updates each state (ILLUSTRATION → ANIMATION → DESIGN). End line fixed at the bottom throughout."],
["Pacing","Ease in and out on every transition. Calm and inevitable, not flashy."]],
eye:"The moment of transformation, then the label change.",hold:"No particles, sparkles or whooshes. Transformation should feel like craft, not effects.",
copy:[["Label (changing)","ILLUSTRATION · ANIMATION · DESIGN"],["End line","One seat. Every shape."]],
li:"Over the last couple of months we’ve made three chairs: one drawn, one animated, one designed.\n\nHere’s the reveal: they’re the same seat. That’s how Creative Seat works. One team plugged into yours, switching between design, illustration and animation as your plan requires, with no new supplier each time.",
ig:"Seats 01, 02 and 03 are the same seat.\n\nDesign, illustration and animation from one creative team, taking whatever shape the brief needs."},

{id:"p18",n:18,t:"Your Seat Is Ready",p:"service",s:"",pl:"LinkedIn + Instagram",f:"Static + 6s animated variant",sz:["1080×1350","1080×1920"],d:"2026-12-22",
obj:"Convert 12 weeks of attention into enquiries with a clear, warm invitation.",
idea:"The volt chair from Post 1, alone in a vast sunlit meadow on a gentle hill, with a pill tag floating beside it: “● Available now”. The feed ends where the anxiety ends: space, calm, capacity.",
ad:[["Composition","Wide landscape. The chair on the brow of a hill in the lower third, small (about 15% of height), under an enormous soft-blue sky. Scale says spaciousness."],
["Style","Dreamy, slightly surreal 3D landscape: saturated greens, tiny wildflowers, soft volumetric light. The chair keeps its clay texture."],
["Tag","A paper pill with a volt dot, “● Available now”, floats top-left like a UI status badge dropped into nature."],
["Headline & CTA","Large ink sans in the sky, second line in Instrument Serif italic. A volt pill button bottom-centre, deliberately tappable-looking."],
["Animated variant","Grass sways, a single cloud drifts, the tag’s dot pulses."]],
eye:"The headline, then down to the small chair.",hold:"No people, no laptops, no stats. It’s an invitation, not a spec sheet.",
copy:[["Tag","● Available now"],["Headline","Your seat is ready."],["CTA button","Take a seat"]],
li:"For the last three months we’ve been posting about queues, resizes, Friday-afternoon quick ones and the empty chair in every planning meeting.\n\nIf any of it felt familiar, this is the part where we help.\n\nCreative Seat gives your marketing team ongoing design, illustration and animation capacity, working as part of your team. Tell us what’s in the backlog and we’ll show you how a seat would work for you.\n\nSend us the brief.",
ig:"Your seat is ready.\n\nDesign, illustration and animation on demand. DM us or tap the link in bio."}
];
